/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import googleMaps from "@amicaldo/strapi-google-maps/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiAdvancedUuid from "strapi-advanced-uuid/strapi-admin";
import fieldNanoid from "strapi-auto-nanoid/strapi-admin";
import countrySelect from "strapi-plugin-country-select/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import tagsinput from "strapi-plugin-tagsinput/strapi-admin";
import customEntityKey from "../../src/plugins/custom-entity-key/strapi-admin";
import silvergenie from "../../src/plugins/silvergenie/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "google-maps": googleMaps,
    "strapi-cloud": strapiCloud,
    documentation: documentation,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-advanced-uuid": strapiAdvancedUuid,
    "field-nanoid": fieldNanoid,
    "country-select": countrySelect,
    "import-export-entries": importExportEntries,
    tagsinput: tagsinput,
    "custom-entity-key": customEntityKey,
    silvergenie: silvergenie,
  },
});
